reworking sbt console to use universal dir

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -98,6 +98,19 @@ fi
 rm -f $SBT_BINDIR/sbt
 cat << EOF > $SBT_BINDIR/sbt
 #!/usr/bin/env bash
+
+if [ "\$@" == "console" ]
+  scalaLibraryJar=\$(ls . | grep "org.scala-lang.scala-library")
+  scalaVersion=\$(expr \${scalaLibraryJar} : "\(2\.[0-9]\+\.[0-9]\+\(\-[a-zA-Z0-9]\+\)\?\)")
+  scalaCompilerJar="scala-compiler-\${scalaVersion}.jar"
+  scalaCompilerUrl="http://central.maven.org/maven2/org/scala-lang/scala-compiler/\${scalaVersion}/\${scalaCompilerJar}"
+
+  curl --silent --max-time 60 -o target/universal/stage/lib/\$scalaCompilerJar \$scalaCompilerUrl --fail || error "Failed to download \${scalaCompilerJar}"
+
+  java -cp target/universal/stage/lib/* scala.tools.nsc.MainGenericRunner -usejavacp
+else
+  echo "[error] Not a valid command: \$@"
+fi
 java  -Duser.home=/app/.sbt_home -Divy.default.ivy.user.dir=/app/.sbt_home/.ivy2 -jar /app/.sbt_home/bin/$SBT_JAR "\$@"
 EOF
 chmod a+x $SBT_BINDIR/sbt
